#!/usr/bin/env python3

from bitcoinkeytool import BitcoinAccount
from ethereumkeytool import EthereumAccount
from ripplekeytool import RippleAccount
    
for n in range(10):   # number of key pairs to generate`

    # generate private key , uncompressed WIF starts with "5", compressed
    # with L or K
    A = BitcoinAccount()
    WIF = A.to_wif()
    
    # get public key , (un)compressed address starts with "1"

    addr = A.to_address()

    i = n + 1
    print('Bitcoin Private Key    ', str(i) + ": " + WIF)
    print("Bitcoin Address", str(i) + ": " + addr)

print("##############")

for n in range(10):   # number of key pairs to generate`

    # generate private key , uncompressed WIF starts with "5"
    B = EthereumAccount()
    
    # get public key , uncompressed address starts with "1"
    priv = B.private_key
    
    addr = B.to_address()

    i = n + 1
    print('Ethereum Private Key    ', str(i) + ": " + priv)
    print("Ethereum Address", str(i) + ": " + addr)

print("##############")

for n in range(10):   # number of key pairs to generate`

    # generate private key , uncompressed WIF starts with "5"
    C = RippleAccount()
    
    # get public key , uncompressed address starts with "1"
    priv = C.private_key
    
    addr = C.to_accountid()

    i = n + 1
    print('Ripple Private Key    ', str(i) + ": " + priv)
    print("Ripple Address", str(i) + ": " + addr)

